apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  clusterName: arn:aws:eks:eu-west-1:827659017777:cluster/eks-mlops
  creationTimestamp: null
  name: eks-mlops
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cluster-local-gateway
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: tensorboard/overlays/istio
    name: tensorboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws
    name: kubeflow-apps
  - kustomizeConfig:
      overlays:
      - oidc
      parameters:
      - name: namespace
        value: istio-system
      - name: oidcIssuer
        value: https://dr-kubeflow.eu.auth0.com/
      - name: oidcAuthorizationEndpoint
        value: https://dr-kubeflow.eu.auth0.com/authorize
      - name: oidcTokenEndpoint
        value: https://dr-kubeflow.eu.auth0.com/oauth/token
      - name: oidcUserInfoEndpoint
        value: https://dr-kubeflow.eu.auth0.com/userinfo
      - name: certArn
        value: arn:aws:acm:eu-west-1:827659017777:certificate/c6a47484-85ab-4aa7-af8b-2b5d511b43dd
      - name: oidcSecretName
        value: alb-oidc-secret
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-ingress-cognito
    name: istio-ingress
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: aws/aws-istio-authz-adaptor/base
    name: aws-istio-authz-adaptor
  plugins:
  - kind: KfAwsPlugin
    metadata:
      creationTimestamp: null
      name: aws
    spec:
      auth:
        oidc:
          certArn: arn:aws:acm:eu-west-1:827659017777:certificate/2374e2ce-3e25-4a5a-b7a4-95be22618952
          oAuthClientId: ailoX8UF9RCQEzW4PyZFLoWoi4uqrf52
          oAuthClientSecret: MZxqATqZkNdmFyax0-nqJGclb_vAvKrD-WugvzBRajRhtgjFw4Clzw_G2bE7temK
          oidcAuthorizationEndpoint: https://dr-kubeflow.eu.auth0.com/authorize
          oidcIssuer: https://dr-kubeflow.eu.auth0.com/
          oidcTokenEndpoint: https://dr-kubeflow.eu.auth0.com/oauth/token
          oidcUserInfoEndpoint: https://dr-kubeflow.eu.auth0.com/userinfo
      enablePodIamPolicy: true
      region: eu-west-1
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz
  version: v1.1-branch
status:
  reposCache:
  - localPath: '".cache/manifests/manifests-1.1-branch"'
    name: manifests
  - localPath: '".cache/manifests/manifests-1.1-branch"'
    name: manifests
