jupyterhub:
  hub:
    services:
      dask-gateway:
        apiToken: ${ daskgateway_secret }
  singleuser:
    profileList:
%{for profile in singleuser_profile_list ~}
      - display_name: ${ profile.display_name }
        description: ${ profile.description }
        default: ${ profile.default }
        kubespawner_override:
          image: ${ profile.kubespawner_override.image }
%{ endfor ~}
    image:
      name: "jupyterhub/k8s-network-tools"
pullPolicy: ${ singleuser_image_pull_policy }
    memory:
      guarantee: ${ singleuser_memory_guarantee }
    storage:
      capacity: ${ singleuser_storage_capacity }
      homeMountPath: ${ singleuser_storage_mount_path }
    extraEnv:
      TZ: "Europe/Berlin"

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: ${ jupyterhub_secret }