jupyterhub:
  hub:
    services:
      dask-gateway:
        apiToken: ${ daskgateway_secret }
  singleuser:
    profileList:
%{for profile in singleuser_profile_list ~}
      - display_name: ${ profile.display_name }
        description: "${ profile.description }"
        default: ${ profile.default }
        kubespawner_override:
          image: ${ profile.kubespawner_override.image }
%{ endfor ~}
    extraEnv:
      TZ: "Europe/Berlin"
    image:
      name: "jupyterhub/k8s-network-tools"
      pullPolicy: ${ singleuser_image_pull_policy }
	  pullSecrets:
%{ for img_pull_secret in singleuser_image_pull_secrets ~}
	  - name: "${ img_pull_secret.name }"
%{ endfor ~}
    memory:
      guarantee: ${ singleuser_memory_guarantee }
    storage:
      capacity: ${ singleuser_storage_capacity }
      homeMountPath: ${ singleuser_storage_mount_path }
dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: ${ jupyterhub_secret }