jupyterhub:
  hub:
    services:
      dask-gateway:
        apiToken: ${ daskgateway_secret }
  singleuser:
    extraEnv:
      DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: 'drtools/openmlops-notebook:v1.2'
    image:
      name: "drtools/openmlops-notebook"
      tag: "v1.2"

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: ${ jupyterhub_secret }