jupyterhub:
  hub:
    services:
      dask-gateway:
        apiToken: ${ daskgateway_secret }
  singleuser:
    profileList: ${ singleuser_profile_list }
    image:
      name: "jupyterhub/k8s-network-tools"
      pullSecrets: ${ singleuser_image_pull_secrets }
      pullPolicy: ${ singleuser_image_pull_policy }
    memory:
      guarantee: ${ singleuser_memory_guarantee }
    storage:
      capacity: ${ singleuser_storage_capacity }
      homeMountPath: ${ singleuser_storage_mount_path }
    extraEnv:
      TZ: "Europe/Berlin"

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: ${ jupyterhub_secret }