hub:
  allowNamedServers: true

proxy:
  https:
    enabled: true
    hosts:
      - lab.thedatarevenue.com
    letsencrypt:
      contactEmail: "pedro@datarevenue.com"
  secretToken: "c98d13315d8d78305e195add8300f86a601181eb2669d8d49fa37140274d129d"

auth:
  type: github
  github:
    clientId: "20589e5b77475ec0bd6e"
    clientSecret: "e310dd8b533f88762f23484bfc3241b0d942b6d4"
    callbackUrl: "https://lab.thedatarevenue.com/hub/oauth_callback"
    orgWhiteList:
      - "datarevenue-berlin"
  admin:
    users:
    - kayibal
    - pedrocwb
    - tamaralipows

  scopes:
    - "read:user"
  
singleuser:
  defaultUrl: /lab
  image:
    pullSecrets:
      - "regcred"
  profileList:
    - display_name: "Minimal environment (default)"
      description: "To avoid too much bells and whistles: Python. \n jupyter/datascience-notebook:lab-2.2.9"
      kubespawner_override:
        image: "jupyter/datascience-notebook:lab-2.2.9"
      default: true

    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia. \n jupyter/datascience-notebook:2343e33dec46"
      kubespawner_override:
        image: "jupyter/datascience-notebook:2343e33dec46"

    - display_name: "Datarevenue custom image"
      description: "Image from datarevenue private repository - drtools/notebook-server:cpu-0.0.1"
      kubespawner_override:
        image: "drtools/notebook-server:cpu-0.0.1"


  memory:
    guarantee: 100M
  storage:
    capacity: 1Gi
    homeMountPath: /home/jovyan/persistent
  extraEnv:
    TZ: Europe/Berlin
